### PR TITLE
43 create 1 unit test and 1 widget test for c3

### PR DESCRIPTION
**Pull request by falniir**
added basic widget tests for the Sign In page widgets and for the form validators of Sign In/Up.

### CODE REVIEW

**Comment by jKm00** [comment]
Is this runnable on iOS now?

**Comment by falniir** [comment]
> Is this runnable on iOS now?

updating to the latest flutter version should make it runnable, I don't have an iOS emulator to check further

**Comment by falniir** [comment]
MeowMicGIF

**Review by jKm00 — APPROVED** [review]
cool tests

**Pull request merged**
